apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    run: video
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: video
  selector:
    run: video
