[tool.poetry]
name = "pairing"
version = "0.0.1"
description = "Pairing service for Code2Gather"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
